# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/srv/workspace/odooAddons-7/addons/omnia_spesometro/ui_spesometro/main_window.ui'
#
# Created: Wed Oct 18 15:06:48 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1193, 940)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_content = QtGui.QWidget(self.centralwidget)
        self.widget_content.setObjectName(_fromUtf8("widget_content"))
        self.gridLayout = QtGui.QGridLayout(self.widget_content)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.widget_content)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_spesometro = QtGui.QWidget()
        self.page_spesometro.setObjectName(_fromUtf8("page_spesometro"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_spesometro)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(20)
        self.gridLayout_3.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_out_file_name = QtGui.QLineEdit(self.page_spesometro)
        self.lineEdit_out_file_name.setObjectName(_fromUtf8("lineEdit_out_file_name"))
        self.gridLayout_3.addWidget(self.lineEdit_out_file_name, 2, 1, 1, 1)
        self.label_out_file_name = QtGui.QLabel(self.page_spesometro)
        self.label_out_file_name.setObjectName(_fromUtf8("label_out_file_name"))
        self.gridLayout_3.addWidget(self.label_out_file_name, 2, 0, 1, 1)
        self.label_date_from = QtGui.QLabel(self.page_spesometro)
        self.label_date_from.setObjectName(_fromUtf8("label_date_from"))
        self.gridLayout_3.addWidget(self.label_date_from, 0, 0, 1, 1)
        self.label_date_to = QtGui.QLabel(self.page_spesometro)
        self.label_date_to.setObjectName(_fromUtf8("label_date_to"))
        self.gridLayout_3.addWidget(self.label_date_to, 1, 0, 1, 1)
        self.pushButton_open_path = QtGui.QPushButton(self.page_spesometro)
        self.pushButton_open_path.setObjectName(_fromUtf8("pushButton_open_path"))
        self.gridLayout_3.addWidget(self.pushButton_open_path, 2, 2, 1, 1)
        self.dateEdit_to = QtGui.QDateEdit(self.page_spesometro)
        self.dateEdit_to.setLocale(QtCore.QLocale(QtCore.QLocale.Italian, QtCore.QLocale.Italy))
        self.dateEdit_to.setObjectName(_fromUtf8("dateEdit_to"))
        self.gridLayout_3.addWidget(self.dateEdit_to, 1, 1, 1, 2)
        self.dateEdit_from = QtGui.QDateEdit(self.page_spesometro)
        self.dateEdit_from.setLocale(QtCore.QLocale(QtCore.QLocale.Italian, QtCore.QLocale.Italy))
        self.dateEdit_from.setDate(QtCore.QDate(2000, 1, 6))
        self.dateEdit_from.setObjectName(_fromUtf8("dateEdit_from"))
        self.gridLayout_3.addWidget(self.dateEdit_from, 0, 1, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.label_progress = QtGui.QLabel(self.page_spesometro)
        self.label_progress.setText(_fromUtf8(""))
        self.label_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.label_progress.setObjectName(_fromUtf8("label_progress"))
        self.verticalLayout_4.addWidget(self.label_progress)
        self.progressBar = QtGui.QProgressBar(self.page_spesometro)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_4.addWidget(self.progressBar)
        self.pushButton_generate_xml = QtGui.QPushButton(self.page_spesometro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_generate_xml.sizePolicy().hasHeightForWidth())
        self.pushButton_generate_xml.setSizePolicy(sizePolicy)
        self.pushButton_generate_xml.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_generate_xml.setFont(font)
        self.pushButton_generate_xml.setObjectName(_fromUtf8("pushButton_generate_xml"))
        self.verticalLayout_4.addWidget(self.pushButton_generate_xml)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page_spesometro)
        self.page_settings = QtGui.QWidget()
        self.page_settings.setObjectName(_fromUtf8("page_settings"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_settings)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.page_settings)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1025, 833))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_sezionali = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sezionali.setFont(font)
        self.label_sezionali.setObjectName(_fromUtf8("label_sezionali"))
        self.horizontalLayout_2.addWidget(self.label_sezionali)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_apply_journals = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_apply_journals.setObjectName(_fromUtf8("pushButton_apply_journals"))
        self.horizontalLayout_2.addWidget(self.pushButton_apply_journals)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.pushButton_help_journal = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_help_journal.setObjectName(_fromUtf8("pushButton_help_journal"))
        self.verticalLayout_5.addWidget(self.pushButton_help_journal)
        self.textEdit_journal = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_journal.sizePolicy().hasHeightForWidth())
        self.textEdit_journal.setSizePolicy(sizePolicy)
        self.textEdit_journal.setMaximumSize(QtCore.QSize(16777215, 130))
        self.textEdit_journal.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_journal.setReadOnly(True)
        self.textEdit_journal.setObjectName(_fromUtf8("textEdit_journal"))
        self.verticalLayout_5.addWidget(self.textEdit_journal)
        self.tableWidget = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(185, 194, 192))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.pushButton_help_imposte = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_help_imposte.setObjectName(_fromUtf8("pushButton_help_imposte"))
        self.verticalLayout_5.addWidget(self.pushButton_help_imposte)
        self.textEdit_imposte = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_imposte.sizePolicy().hasHeightForWidth())
        self.textEdit_imposte.setSizePolicy(sizePolicy)
        self.textEdit_imposte.setAutoFillBackground(True)
        self.textEdit_imposte.setFrameShape(QtGui.QFrame.Box)
        self.textEdit_imposte.setFrameShadow(QtGui.QFrame.Plain)
        self.textEdit_imposte.setLineWidth(1)
        self.textEdit_imposte.setReadOnly(True)
        self.textEdit_imposte.setObjectName(_fromUtf8("textEdit_imposte"))
        self.verticalLayout_5.addWidget(self.textEdit_imposte)
        self.tableWidget_imposte = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget_imposte.setObjectName(_fromUtf8("tableWidget_imposte"))
        self.tableWidget_imposte.setColumnCount(8)
        self.tableWidget_imposte.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_imposte.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_imposte.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_imposte.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_imposte.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_imposte.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_imposte.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_imposte.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_imposte.setHorizontalHeaderItem(7, item)
        self.tableWidget_imposte.horizontalHeader().setVisible(True)
        self.tableWidget_imposte.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_imposte.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_imposte.horizontalHeader().setHighlightSections(True)
        self.tableWidget_imposte.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_imposte.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_imposte.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tableWidget_imposte)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_settings)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_content)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_ok = QtGui.QPushButton(self.centralwidget)
        self.pushButton_ok.setObjectName(_fromUtf8("pushButton_ok"))
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_login = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButton_login.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_login.setObjectName(_fromUtf8("pushButton_login"))
        self.verticalLayout.addWidget(self.pushButton_login)
        self.pushButton_spesometro = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButton_spesometro.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_spesometro.setDefault(True)
        self.pushButton_spesometro.setObjectName(_fromUtf8("pushButton_spesometro"))
        self.verticalLayout.addWidget(self.pushButton_spesometro)
        self.pushButton_settings = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButton_settings.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_settings.setObjectName(_fromUtf8("pushButton_settings"))
        self.verticalLayout.addWidget(self.pushButton_settings)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_out_file_name.setText(_translate("MainWindow", "Out File Path", None))
        self.label_date_from.setText(_translate("MainWindow", "Date From", None))
        self.label_date_to.setText(_translate("MainWindow", "Date To", None))
        self.pushButton_open_path.setText(_translate("MainWindow", "...", None))
        self.dateEdit_to.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy", None))
        self.dateEdit_from.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy", None))
        self.pushButton_generate_xml.setText(_translate("MainWindow", "Generate xml", None))
        self.label_sezionali.setText(_translate("MainWindow", "Sezionali", None))
        self.pushButton_apply_journals.setText(_translate("MainWindow", "Apply", None))
        self.pushButton_help_journal.setText(_translate("MainWindow", "Help", None))
        self.textEdit_journal.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Esempio compilazione codici</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">TD01</span>    Fattura</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">TD04</span>    Nota di credito</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">TD05</span>    Nota di debito   </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">TD10</span>    Fattura acquisto IntraUE di beni</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">TD11</span>    Fattura acquisto IntraUE di servizi</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">TD07</span>    Fattura semplificata</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">TD08</span>    Nota di credito semplificata</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Out Code", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Odoo Code", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Odoo Name", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Journal Type", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ID Odoo", None))
        self.pushButton_help_imposte.setText(_translate("MainWindow", "Help", None))
        self.textEdit_imposte.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Valori possibili per il campo <span style=\" font-weight:600;\">Natura</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">N1    </span>escluse ex art. 15</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">N2</span>    non soggette</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">N3</span>    non imponibili</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">N4</span>    esenti</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">N5</span>    regime del margine / IVA non esposta in fattura</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">N6</span>    inversione contabile (per le operazioni in reverse charge ovvero nei casi di autofatturazione per acquisti extra UE di servizi ovvero per importazioni di beni nei soli casi previsti)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">N7</span>    IVA assolta in altro stato UE (vendite a distanza ex art. 40 c. 3 e 4 e art. 41 c. 1 lett. b,  DL 331/93; prestazione di servizi di telecomunicazioni, tele-radiodiffusione ed elettronici ex art. 7-sexies lett. f, g, art. 74-sexies DPR 633/72)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Detraibile    </span>formato numerico; i decimali vanno separati dall\'intero con il carattere  \'.\' (punto)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Deducibile    </span>valori ammessi:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    [SI] = spesa deducibile</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Esigibilità IVA</span>   valori ammessi:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    [I]: IVA ad esigibilità immediata</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    [D]: IVA ad esigibilità differita</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    [S]: scissione dei pagamenti\\n</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tableWidget_imposte.setSortingEnabled(True)
        item = self.tableWidget_imposte.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome Conto", None))
        item = self.tableWidget_imposte.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Codice Conto", None))
        item = self.tableWidget_imposte.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Note Conto", None))
        item = self.tableWidget_imposte.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ID Odoo", None))
        item = self.tableWidget_imposte.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Natura", None))
        item = self.tableWidget_imposte.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Detraibile", None))
        item = self.tableWidget_imposte.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Deducibile", None))
        item = self.tableWidget_imposte.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Esigibilità IVA", None))
        self.pushButton_ok.setText(_translate("MainWindow", "Ok", None))
        self.pushButton_login.setText(_translate("MainWindow", "Login", None))
        self.pushButton_spesometro.setText(_translate("MainWindow", "Spesometro", None))
        self.pushButton_settings.setText(_translate("MainWindow", "Settings", None))

