# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/srv/workspace/odooAddons-7/addons/omnia_spesometro/ui_spesometro/main_window.ui'
#
# Created: Thu Oct  5 16:01:22 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(938, 831)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_spesometro = QtGui.QWidget()
        self.page_spesometro.setObjectName(_fromUtf8("page_spesometro"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_spesometro)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_generate_xml = QtGui.QPushButton(self.page_spesometro)
        self.pushButton_generate_xml.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_generate_xml.setFont(font)
        self.pushButton_generate_xml.setObjectName(_fromUtf8("pushButton_generate_xml"))
        self.horizontalLayout_3.addWidget(self.pushButton_generate_xml)
        self.pushButton_download = QtGui.QPushButton(self.page_spesometro)
        self.pushButton_download.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_download.setFont(font)
        self.pushButton_download.setObjectName(_fromUtf8("pushButton_download"))
        self.horizontalLayout_3.addWidget(self.pushButton_download)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_date_from = QtGui.QLabel(self.page_spesometro)
        self.label_date_from.setObjectName(_fromUtf8("label_date_from"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_date_from)
        self.dateEdit_from = QtGui.QDateEdit(self.page_spesometro)
        self.dateEdit_from.setLocale(QtCore.QLocale(QtCore.QLocale.Italian, QtCore.QLocale.Italy))
        self.dateEdit_from.setDate(QtCore.QDate(2000, 1, 6))
        self.dateEdit_from.setObjectName(_fromUtf8("dateEdit_from"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateEdit_from)
        self.label_date_to = QtGui.QLabel(self.page_spesometro)
        self.label_date_to.setObjectName(_fromUtf8("label_date_to"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_date_to)
        self.dateEdit_to = QtGui.QDateEdit(self.page_spesometro)
        self.dateEdit_to.setLocale(QtCore.QLocale(QtCore.QLocale.Italian, QtCore.QLocale.Italy))
        self.dateEdit_to.setObjectName(_fromUtf8("dateEdit_to"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateEdit_to)
        self.label_out_file_name = QtGui.QLabel(self.page_spesometro)
        self.label_out_file_name.setObjectName(_fromUtf8("label_out_file_name"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_out_file_name)
        self.lineEdit_out_file_name = QtGui.QLineEdit(self.page_spesometro)
        self.lineEdit_out_file_name.setObjectName(_fromUtf8("lineEdit_out_file_name"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_out_file_name)
        self.gridLayout_3.addLayout(self.formLayout, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_spesometro)
        self.page_settings = QtGui.QWidget()
        self.page_settings.setObjectName(_fromUtf8("page_settings"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_settings)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_sezionali = QtGui.QLabel(self.page_settings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_sezionali.setFont(font)
        self.label_sezionali.setObjectName(_fromUtf8("label_sezionali"))
        self.horizontalLayout_2.addWidget(self.label_sezionali)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_apply_journals = QtGui.QPushButton(self.page_settings)
        self.pushButton_apply_journals.setObjectName(_fromUtf8("pushButton_apply_journals"))
        self.horizontalLayout_2.addWidget(self.pushButton_apply_journals)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtGui.QTableWidget(self.page_settings)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(185, 194, 192))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_settings)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_ok = QtGui.QPushButton(self.centralwidget)
        self.pushButton_ok.setObjectName(_fromUtf8("pushButton_ok"))
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(self.centralwidget)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_login = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButton_login.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_login.setObjectName(_fromUtf8("pushButton_login"))
        self.verticalLayout.addWidget(self.pushButton_login)
        self.pushButton_spesometro = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButton_spesometro.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_spesometro.setDefault(True)
        self.pushButton_spesometro.setObjectName(_fromUtf8("pushButton_spesometro"))
        self.verticalLayout.addWidget(self.pushButton_spesometro)
        self.pushButton_settings = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButton_settings.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_settings.setObjectName(_fromUtf8("pushButton_settings"))
        self.verticalLayout.addWidget(self.pushButton_settings)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_generate_xml.setText(_translate("MainWindow", "Generate xml", None))
        self.pushButton_download.setText(_translate("MainWindow", "Download", None))
        self.label_date_from.setText(_translate("MainWindow", "Date From", None))
        self.dateEdit_from.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy", None))
        self.label_date_to.setText(_translate("MainWindow", "Date To", None))
        self.dateEdit_to.setDisplayFormat(_translate("MainWindow", "MM/dd/yyyy", None))
        self.label_out_file_name.setText(_translate("MainWindow", "Out File Name", None))
        self.label_sezionali.setText(_translate("MainWindow", "Sezionali", None))
        self.pushButton_apply_journals.setText(_translate("MainWindow", "Apply", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Out Code", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Odoo Code", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Odoo Name", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Journal Type", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ID Odoo", None))
        self.pushButton_ok.setText(_translate("MainWindow", "Ok", None))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel", None))
        self.pushButton_login.setText(_translate("MainWindow", "Login", None))
        self.pushButton_spesometro.setText(_translate("MainWindow", "Spesometro", None))
        self.pushButton_settings.setText(_translate("MainWindow", "Settings", None))

